version: '3.8'

services:

  api-server-1:
    container_name: api-server-1
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3000
      - ID=1
      - NODE_ENV=development
    ports:
      - 3001:3000 
    volumes:
       - ./api:/usr/src/app         # Mount the api folder to the container’s workdir
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
