version: '3.8'

services:
  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.11.0-debian}
    restart: always
    volumes:
      - ./apisix/conf/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    env_file:
      - .env
    environment:
      - APISIX_STAND_ALONE=true
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:

  api-server-1:
    container_name: api-server-1
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - PORT=3000
      - ID=1
      - NODE_ENV=development
    ports:
      - 3001:3000 
    volumes:
       - ./api:/usr/src/app         # Mount the api folder to the container’s workdir
    networks:
      apisix:

networks:
  apisix:
    driver: bridge
