version: '3.8'

services:
  api-dev:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
       - ./api:/usr/src/app         # Mount the api folder to the container’s workdir
       - /usr/src/app/node_modules  # Prevent node_modules overwrite