version: '3.8'

services:
  etcd:
    image: bitnami/etcd:latest
    restart: always
    env_file:
      - .env
    environment:
      ETCD_ENABLE_V2: 'true'
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_ADVERTISE_CLIENT_URLS: 'http://0.0.0.0:2379'
      ETCD_LISTEN_CLIENT_URLS: 'http://0.0.0.0:2379'
    ports:
      - "2379:2379/tcp"
    networks:
      apisix:

  apisix:
    image: apache/apisix:${APISIX_IMAGE_TAG:-3.11.0-debian}
    restart: always
    volumes:
      - ./apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    env_file:
      - .env
    environment:
      APISIX_ENABLE_ADMIN: 'true' # Enable Admin API
      APISIX_ETCD_HOST: 'http://etcd:2379'
      APISIX_ADMIN_API_PASSWORD: '${APISIX_ADMIN_API_PASSWORD}' # Secure Admin API access
    user: root
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
      - "9092:9092/tcp"
    networks:
      apisix:
    depends_on:
      - etcd
      - api-server-1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://etcd:2379/version" ]
      interval: 10s
      retries: 5
      timeout: 5s

  restore-config:
    image: curlimages/curl:latest
    depends_on:
      - apisix
      - etcd
    env_file:
      - .env
    environment:
      APISIX_ADMIN_API_HOST: '${APISIX_ADMIN_API_HOST}'
      APISIX_ADMIN_API_PASSWORD: '${APISIX_ADMIN_API_PASSWORD}'
    user: root
    volumes:
      - ./etcd/backups:/etcd/backups:ro
      - ./etcd/restore-config.sh:/usr/local/bin/restore-config.sh:ro
    entrypoint: ["/bin/sh", "/usr/local/bin/restore-config.sh"]
    networks:
      apisix:

  api-server-1:
    container_name: api-server-1
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      PORT: '3000'
      ID: '1'
      NODE_ENV: 'development'
      MONGO_HOST: 'mongodb'
      MONGO_PORT: '27017'
      MONGO_PATH: '${MONGO_PATH}'
      MONGO_USER: '${MONGO_USER}'
      MONGO_PASSWORD: '${MONGO_PASSWORD}'
      JWT_SECRET: '${JWT_SECRET}'
      APISIX_ADMIN_API_HOST: '${APISIX_ADMIN_API_HOST}'
      APISIX_ADMIN_API_PASSWORD: '${APISIX_ADMIN_API_PASSWORD}'
    ports:
      - 3001:3000 
    volumes:
       - ./api:/usr/src/app         # Mount the api folder to the container’s workdir
    networks:
      apisix:
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:7.0.0
    environment:
      MONGO_INITDB_DATABASE: '${MONGO_PATH}'
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USER}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
    ports:
      - '27017:27017'
    volumes:
      - db:/data/db
    networks:
      apisix:

networks:
  apisix:
    driver: bridge

volumes:
  db:
