# Use an official Node.js runtime as a parent image
FROM node:18

# Create and define the node_modules's cache directory.
RUN mkdir /usr/src/cache
WORKDIR /usr/src/cache

# Copy package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies, including dev dependencies
RUN npm install
  
# Set working directory inside the container
WORKDIR /usr/src/app
  
# Set the entrypoint
ENTRYPOINT ["bash", "entrypoint.sh"]
