# Archivo que permite realizar pruebas desde vscode mediante el uso de la extensión REST Client

// HTTP request to the API
GET http://localhost:3000/api

###

// Register an user with username and password
POST https://localhost:9443/api/auth/register
Content-Type: application/json

{
    "username": "jorge",
    "password": "password"
}

###

// Get user info
GET https://localhost:9443/api/user/me
Content-Type: application/json
Authorization: Basic jorge:password

###

// Activate simple function with array of parameters
POST https://localhost:9443/api/function/queue
Content-Type: application/json
Authorization: Basic jorge:password

{
  "image": "o4tmeal/function-container:latest",
  "parameters": ["4", "80"]
}  

###

// Activate function with JSON parameters
POST https://localhost:9443/api/function/queue
Content-Type: application/json
Authorization: Basic jorge:password

{
  "image": "o4tmeal/json-function-container:latest",
  "parameters": "{\"a\": 5, \"b\": 10}"
}

###

// Activate long running function (5 minutes)
POST https://localhost:9443/api/function/queue
Content-Type: application/json
Authorization: Basic jorge:password

{
  "image": "o4tmeal/long-task-container",
  "parameters": ""
}

###

// Activate a function that connects to the internet 
POST https://localhost:9443/api/function/queue
Content-Type: application/json
Authorization: Basic jorge:password

{
  "image": "o4tmeal/web-function:latest",
  "parameters": ""
}

###

// Activate a function that only has cmd
POST https://localhost:9443/api/function/queue
Content-Type: application/json
Authorization: Basic jorge:password

{
  "image": "o4tmeal/web-function:cmd",
  "parameters": ""
}
